import type { CandidateRecord } from "./candidateTypes";

export const CANDIDATES_STORAGE_KEY = "candidatePool_candidates_v1";

export const SEED_CANDIDATES: CandidateRecord[] = [
  {
    id: "1",
    initials: "SJ",
    name: "Janshika",
    email: "janshika@example.com",
    role: "Senior UX Designer",
    skills: ["React", "Node.js", "Figma"],
    extraSkillsCount: 3,
    location: "Berlin, Germany",
    experience: "6 Years",
    status: "In Review",
    statusTone: "blue",
    category: "Lead / Director",
    verificationStatus: "Pending Review",
    lastActiveLabel: "2 mins ago",
    phone: "+49 30 555 0101",
  },
  {
    id: "2",
    initials: "MK",
    name: "Thushainini",
    email: "thushai@example.com",
    role: "Backend Engineer",
    skills: ["Python", "AWS"],
    extraSkillsCount: 2,
    location: "Austin, TX",
    experience: "8 Years",
    status: "New",
    statusTone: "gray",
    category: "Mid-Level",
    verificationStatus: "Not Yet Reviewed",
    lastActiveLabel: "Yesterday",
    phone: "+1 512 555 0198",
  },
  {
    id: "3",
    initials: "SL",
    name: "Sarah",
    email: "sarah@design.co",
    role: "Product Designer",
    skills: ["Figma", "UI/UX"],
    location: "London, UK",
    experience: "4 Years",
    status: "New",
    statusTone: "gray",
    category: "Mid-Level",
    verificationStatus: "Profile Submitted",
    lastActiveLabel: "3 days ago",
  },
  {
    id: "4",
    initials: "DR",
    name: "Heli",
    email: "heli@stream.com",
    role: "Staff Engineer",
    skills: ["Go", "Kubernetes"],
    extraSkillsCount: 5,
    location: "Remote",
    experience: "10 Years",
    status: "Withdrawn",
    statusTone: "red",
    category: "Lead / Director",
    verificationStatus: "Viewed by Admin",
    lastActiveLabel: "Last week",
    phone: "+1 415 555 0142",
  },
  {
    id: "5",
    initials: "AL",
    name: "Shavindi",
    email: "shavindi@creative.net",
    role: "Frontend Developer",
    skills: ["Vue.js", "Tailwind"],
    location: "Singapore",
    experience: "3 Years",
    status: "In Review",
    statusTone: "blue",
    category: "Junior",
    verificationStatus: "Under Admin Review",
    lastActiveLabel: "10 mins ago",
  },
];
